# Site settings
author: Kenneth Colon
title: 
header-img: img/home-bg.png
email: kennethmanuel250@gmail.com
copyright_name: Kenneth Colon
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ken025

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
